on:
    push:
        branches: main

name: Build and deploy to GitHub Pages

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: build_and_deploy
              uses: shalzz/zola-deploy-action@v0.14.1
              env:
                  PAGES_BRANCH: gh-pages
                  TOKEN: ${{ secrets.TOKEN }}
